version: '3.8'
services:
    # laravel.test:
    #     build:
    #         context: ./docker/8.2
    #         dockerfile: Dockerfile
    #         args:
    #             WWWGROUP: '${WWWGROUP}'
    #     image: sail-8.2/app
    #     extra_hosts:
    #         - 'host.docker.internal:host-gateway'
    #     ports:
    #         - '${APP_PORT:-80}:80'
    #         - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    #     environment:
    #         WWWUSER: '${WWWUSER}'
    #         LARAVEL_SAIL: 1
    #         XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
    #         XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
    #         IGNITION_LOCAL_SITES_PATH: '${PWD}'
    #     volumes:
    #         - '.:/var/www/html'
    #     networks:
    #         - sail
    #     depends_on:
    #         - mysql
    #         - redis
    #         - mailpit
    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            # MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - './sail-mysql:/var/lib/mysql'
            - './my.cnf:/etc/mysql/my.cnf'
            - './logs:/var/log/mysql'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    postgres:
        image: postgres:13
        ports:
            - '5432:5432'
        # restart: always
        environment:
            # POSTGRES_DB: 'typebot'
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: '${DB_PASSWORD}'
        volumes:
            - './sail-postgres:/var/lib/postgresql/data'
        networks:
            - sail
    # minio:
    #     image: minio/minio
    #     command: server /data --console-address ":9001"
    #     ports:
    #         - '9002:9000'
    #         - '9001:9001'
    #     environment:
    #         MINIO_ROOT_USER: '${MINIO_ROOT_USER}'
    #         MINIO_ROOT_PASSWORD: '${MINIO_ROOT_PASSWORD}'
    #     volumes:
    #         - './sail-minio:/data'
    # This service just make sure a bucket with the right policies is created
    # createbuckets:
    #     image: minio/mc
    #     depends_on:
    #         - minio
    #     entrypoint: >
    #         /bin/sh -c "
    #         sleep 10;
    #         /usr/bin/mc config host add minio http://minio:9002 minio password;
    #         /usr/bin/mc mb minio/typebot;
    #         /usr/bin/mc anonymous set public minio/typebot/public;
    #         exit 0;
    #         "
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - './sail-redis:/data'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
    phpmyadmin:
        depends_on:
            - mysql
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            UPLOAD_LIMIT: 999M
            MEMORY_LIMIT: 999M
            MAX_EXECUTION_TIME: 300
        networks:
            - sail
        ports:
            - 8083:80
    adminer:
        depends_on:
            - postgres
        image: adminer
        ports:
            - 8084:8080
        environment:
            ADMINER_DEFAULT_SERVER: postgres
        networks:
            - sail
    # phpredisadmin:
    #     depends_on:
    #         - redis
    #     image: erikdubbelboer/phpredisadmin
    #     ports:
    #         - 8082:80
    #     environment:
    #         - REDIS_1_HOST=redis
    #         # - REDIS_1_NAME=redis
    #         - REDIS_1_PORT=6379
    #     networks:
    #         - sail
    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
    sail-postgres:
        driver: local
    sail-minio:
        driver: local
    sail-redis:
        driver: local